"""new migration

Revision ID: b4e8f09ee7cb
Revises: 5e36970dc040
Create Date: 2024-12-05 02:40:55.205537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e8f09ee7cb'
down_revision: Union[str, None] = '5e36970dc040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('completed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
