# Generated by Django 5.1.3 on 2024-11-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_recipe_my_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='my_favourite',
            new_name='favorites',
        ),
    ]
